### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by hexodotsh** [aleemladha/ludus_exchange#1]
Hi,

How do i use this, theres no inventory.yml

**Comment by aleemladha** [comment]
Hi,

Just add the role 

# Add the role to your ludus host
ludus ansible roles add aleemladha.ludus_exchange

under your config.yml file 

domain:
      fqdn: ludus.domain
      role: primary-dc
    roles:
      - aleemladha.ludus_exchange

Do you have a specific use case..
